version: "3"
services:
  # crawler:
  #   image: "nekia/crawler-linea:1.0.0"
  scanner:
    image: "nekia/scanner-linea:1.0.0"
    deploy:
      replicas: 3
    environment:
      - NATS_SERVER_URL=nats-server:4222
    depends_on:
      - nats-server
  mediator:
    image: "nekia/mediator:1.0.0"
    environment:
      - NATS_SERVER_URL=nats-server:4222
    depends_on:
      - nats-server
  notifier:
    image: "nekia/notifier:1.0.0"
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - CACHE_MGR_URL=cache-mgr:50051
      - LINE_NOTIFY_TOKEN=<YOUR LINE NOTIFY TOKEN>
    depends_on:
      - nats-server
      - mediator
      - cache-mgr
  cache-mgr:
    image: "nekia/cache-mgr:1.0.0"
    ports:
      - 50051:50051
    environment:
      - IGNORE_INSPECTED_CACHE=1
      - REDIS_SERVER_URL=redis://192.168.2.132:31951
  nats-server:
    image: "nats:2.7.4"
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: -js
