version: "3"
services:
  # crawler:
  #   image: "nekia/crawler-linea:1.0.0"
  crawler-linea-ngy:
    image: "nekia/crawler-homes:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=host.docker.internal:4222
      - CACHE_MGR_URL=host.docker.internal:50051
    volumes:
      - ./crawler/homes/setting-ngy-rent:/usr/src/app/setting
