version: "3"
services:
  # crawler:
  #   image: "crawler-linea:1.0.0"
  crawler-linea-ngy:
    image: "crawler-homes:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=host.docker.internal:4222
      - CACHE_MGR_URL=host.docker.internal:50051
    volumes:
      - ./crawler/homes/setting-ngy-rent:/usr/src/app/setting
