FROM ubuntu:18.04 as build

WORKDIR /usr/src/app
RUN apt update && \
    apt -y install wget tar && \
    arch=$(arch | sed s/aarch64/arm64/ | sed s/x86_64/amd64/) && \
    wget "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-${arch}.tgz" && \
    tar xf "ngrok-v3-stable-linux-${arch}.tgz"

FROM gcr.io/distroless/base-debian11

COPY --from=build /usr/src/app/ngrok /usr/bin/ngrok
CMD ["ngrok", "start", "--all"]