version: "3"
services:
  # crawler:
  #   image: "nekia/crawler-linea:1.0.0"
  scanner-linea:
    image: "nekia/scanner-linea:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - NATS_SUBJECT_ROOMURL=room-linea-tky-rent
      - NATS_SUBJECT_ROOMDETAIL=roomdetails-tky-rent
    depends_on:
      - nats-server
  scanner-suumo:
    image: "nekia/scanner-suumo:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - NATS_SUBJECT_ROOMURL=room-suumo-tky-rent
      - NATS_SUBJECT_ROOMDETAIL=roomdetails-tky-rent
    depends_on:
      - nats-server
  scanner-homes:
    image: "nekia/scanner-homes:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - NATS_SUBJECT_ROOMURL=room-homes-tky-rent
      - NATS_SUBJECT_ROOMDETAIL=roomdetails-tky-rent
    depends_on:
      - nats-server
  scanner-homes-ngy:
    image: "nekia/scanner-homes:1.0.0"
    deploy:
      replicas: 1
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - NATS_SUBJECT_ROOMURL=room-homes-ngy-rent
      - NATS_SUBJECT_ROOMDETAIL=roomdetails-ngy-rent
    depends_on:
      - nats-server
  mediator:
    image: "nekia/mediator:1.0.0"
    environment:
      - NATS_SERVER_URL=nats-server:4222
    depends_on:
      - nats-server
  notifier:
    image: "nekia/notifier:1.0.0"
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - CACHE_MGR_URL=cache-mgr:50051
      - LINE_NOTIFY_TOKEN=<YOUR LINE NOTIFY TOKEN>
      - ENABLE_NOTIFY=0
    depends_on:
      - nats-server
      - cache-mgr
  notifier-ngy:
    image: "nekia/notifier:1.0.0"
    environment:
      - NATS_SERVER_URL=nats-server:4222
      - CACHE_MGR_URL=cache-mgr:50051
      - LINE_NOTIFY_TOKEN=<YOUR LINE NOTIFY TOKEN>
      - ENABLE_NOTIFY=1
    depends_on:
      - nats-server
      - cache-mgr
      - scanner-homes-ngy
    volumes:
      - ./notification/setting-ngy-rent:/usr/src/app/setting
  cache-mgr:
    image: "nekia/cache-mgr:1.0.0"
    ports:
      - 50051:50051
    environment:
      - IGNORE_INSPECTED_CACHE=0
      - ENABLE_CACHE=0
      - REDIS_SERVER_URL=redis://192.168.2.132:31951
  nats-server:
    image: "nats:2.7.4"
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    command: -js
